//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BD_LogisticaTransporteEntities : DbContext
    {
        public BD_LogisticaTransporteEntities()
            : base("name=BD_LogisticaTransporteEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        public void Dispose()
        {
            throw new NotImplementedException();
        }

        public virtual DbSet<Agentes_Aduanales> Agentes_Aduanales { get; set; }
        public virtual DbSet<CodigoPostal> CodigoPostal { get; set; }
        public virtual DbSet<Contribuyentes> Contribuyentes { get; set; }
        public virtual DbSet<Direcciones> Direcciones { get; set; }
        public virtual DbSet<Empleados> Empleados { get; set; }
        public virtual DbSet<Equipo_Transporte> Equipo_Transporte { get; set; }
        public virtual DbSet<Modulos> Modulos { get; set; }
        public virtual DbSet<Pedimento> Pedimento { get; set; }
        public virtual DbSet<Rel_AA> Rel_AA { get; set; }
        public virtual DbSet<Rel_Pedimento_Empleado> Rel_Pedimento_Empleado { get; set; }
        public virtual DbSet<Rel_TipoUsuario_Modulos> Rel_TipoUsuario_Modulos { get; set; }
        public virtual DbSet<Rel_TipoUsuario_Submodulos> Rel_TipoUsuario_Submodulos { get; set; }
        public virtual DbSet<Servicios> Servicios { get; set; }
        public virtual DbSet<Submodulos> Submodulos { get; set; }
        public virtual DbSet<Tipo_Usuario> Tipo_Usuario { get; set; }
        public virtual DbSet<Usuarios> Usuarios { get; set; }
    }
}
