//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class CodigoPostal
    {
        public int CP { get; set; }
        public string Col { get; set; }
        public string DelMun { get; set; }
        public string Ciudad { get; set; }
        public string EntidadFederativa { get; set; }
        public string Pais { get; set; }
    }
}
