//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contribuyentes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Contribuyentes()
        {
            this.Rel_AA = new HashSet<Rel_AA>();
            this.Pedimento = new HashSet<Pedimento>();
        }
    
        public int ID_Contribuyente { get; set; }
        public Nullable<int> Tipo { get; set; }
        public string Nombre { get; set; }
        public string RFC { get; set; }
        public string Telefono { get; set; }
        public string Correo { get; set; }
        public byte[] IMG_Empresa { get; set; }
        public Nullable<int> No_Empleados { get; set; }
        public Nullable<System.DateTime> Fecha_Alta { get; set; }
        public Nullable<System.DateTime> Fecha_Baja { get; set; }
        public Nullable<bool> Activo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rel_AA> Rel_AA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pedimento> Pedimento { get; set; }
        public virtual Empleados Empleados { get; set; }
    }
}
