//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Direcciones
    {
        public int ID_Direccion { get; set; }
        public Nullable<int> ID_Contribuyente { get; set; }
        public string Calle { get; set; }
        public string Manzana { get; set; }
        public string Lote { get; set; }
        public string No_Ext { get; set; }
        public string No_Int { get; set; }
        public Nullable<int> CP { get; set; }
    }
}
