//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empleados
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Empleados()
        {
            this.Rel_Pedimento_Empleado = new HashSet<Rel_Pedimento_Empleado>();
        }
    
        public int ID_Empleado { get; set; }
        public string Nombre { get; set; }
        public string Ap_Pat { get; set; }
        public string Ap_Mat { get; set; }
        public string RFC { get; set; }
        public string NSS { get; set; }
        public string ContratoTXT { get; set; }
        public byte[] ContratoIMG { get; set; }
        public Nullable<decimal> Sueldo { get; set; }
        public Nullable<decimal> Bonos { get; set; }
        public string Tipo_Emp { get; set; }
        public Nullable<System.DateTime> Fecha_Alta { get; set; }
        public Nullable<System.DateTime> Fecha_Baja { get; set; }
        public Nullable<bool> Activo { get; set; }
    
        public virtual Contribuyentes Contribuyentes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rel_Pedimento_Empleado> Rel_Pedimento_Empleado { get; set; }
    }
}
