//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pedimento
    {
        public int ID_Pedimento { get; set; }
        public Nullable<int> ID_Contribuyente { get; set; }
        public Nullable<int> ID_ET { get; set; }
        public Nullable<int> ID_Servicio { get; set; }
        public string Origen { get; set; }
        public string Destino { get; set; }
        public Nullable<decimal> KM { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<System.TimeSpan> HoraSalida { get; set; }
        public Nullable<System.TimeSpan> HoraRegreso { get; set; }
        public Nullable<System.DateTime> FechaSalida { get; set; }
        public Nullable<System.DateTime> FechaRegreso { get; set; }
    
        public virtual Contribuyentes Contribuyentes { get; set; }
        public virtual Equipo_Transporte Equipo_Transporte { get; set; }
        public virtual Servicios Servicios { get; set; }
    }
}
