//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rel_TipoUsuario_Modulos
    {
        public string ID_Rel_TU_M { get; set; }
        public string ID_TipoUsuario { get; set; }
        public string ID_Modulo { get; set; }
    
        public virtual Tipo_Usuario Tipo_Usuario { get; set; }
    }
}
