//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuarios
    {
        public int ID_Usuario { get; set; }
        public string ID_TipoUsuario { get; set; }
        public string Nombre { get; set; }
        public string Pass { get; set; }
        public string ID_Empresa { get; set; }
        public Nullable<System.DateTime> Fecha_Alta { get; set; }
        public Nullable<System.DateTime> Fecha_Baja { get; set; }
        public Nullable<bool> Activo { get; set; }
    }
}
